# Generated by Django 5.2.3 on 2025-06-26 01:24

import bond.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=10)),
                ('descricao', models.CharField(max_length=50, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('imagem1', models.ImageField(blank=True, null=True, upload_to='banners/')),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('bv_desc', models.CharField(max_length=60)),
                ('descricao', models.CharField(max_length=300)),
                ('funcao', models.CharField(max_length=60)),
                ('tags', models.CharField(max_length=40)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='imagens_produtos')),
                ('data_adicionada', models.DateField(auto_now=True)),
                ('data_prazo', models.PositiveBigIntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('visualizacao', models.PositiveIntegerField(default=0)),
                ('vendas', models.PositiveIntegerField(default=0)),
                ('avaliacao_anuncio', models.CharField(max_length=2)),
                ('tipo', models.CharField(choices=[('produto', 'Produto'), ('servico', 'Servico')], max_length=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria_produto', to='bond.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avaliacao', models.PositiveBigIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('anuncio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bond.anuncio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.PositiveIntegerField(default=0)),
                ('data_criado', models.DateField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Confiabilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_membro', models.DateField(auto_now=True)),
                ('ultimo_acesso', models.DateTimeField(blank=True, null=True)),
                ('nivel_confiavel', models.IntegerField(blank=True, default=0)),
                ('imagemDoc', models.ImageField(blank=True, null=True, upload_to='docs')),
                ('email', models.BooleanField(blank=True, default=False)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5)),
                ('valor_antigo', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creditos_usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sobre', models.CharField(max_length=200)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('data_nas', models.DateTimeField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='users')),
                ('confiabilidade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='confiabilidade', to='bond.confiabilidade')),
                ('creditos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creditosCustom', to='bond.credito')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(blank=True, max_length=100, null=True)),
                ('avaliacao', models.IntegerField(default=0)),
                ('data_create', models.DateField(auto_now_add=True, null=True)),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bond.anuncio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('customUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bond.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='EmailToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mensagem_Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=60)),
                ('status', models.CharField(choices=[('Recusada', 'Recusada'), ('Pendente', 'Pendente'), ('Confirmada', 'Confirmada')], default='Pendente', max_length=20)),
                ('mensagem', models.CharField(max_length=400)),
                ('user_env', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_env_manager', to=settings.AUTH_USER_MODEL)),
                ('user_rec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_rec_manager', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mensagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=60)),
                ('mensagem', models.CharField(max_length=400)),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Enviada', 'Enviada'), ('Recebida', 'Recebida')], default='Pendente', max_length=20)),
                ('data', models.DateField(auto_now_add=True, null=True)),
                ('user_env', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_env', to=settings.AUTH_USER_MODEL)),
                ('user_rec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_rec', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_carrinho', models.DecimalField(decimal_places=2, max_digits=5)),
                ('carrinho_str', models.CharField(blank=True, max_length=100, null=True)),
                ('status_pagamento', models.CharField(blank=True, choices=[('Pendente', 'Pendente'), ('Concluida', 'Concluida'), ('Recusada', 'Recusada')], max_length=20)),
                ('status_pedido', models.CharField(blank=True, choices=[('Pendente', 'Pendente'), ('Concluida', 'Concluida'), ('Recusada', 'Recusada')], max_length=20)),
                ('metodo_pagamento', models.CharField(blank=True, choices=[('Creditos', 'Creditos'), ('Pix', 'Pix')], max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('comprovante', models.ImageField(blank=True, null=True, upload_to=bond.models.upload_to)),
                ('confirm_client', models.BooleanField(default=False)),
                ('carrinho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Carrinho_pedido', to='bond.carrinho')),
                ('user_remetente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_rementente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('ultimo_nome', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bond.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Produto_Carrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avaliacao', models.PositiveIntegerField()),
                ('quantidade', models.PositiveIntegerField()),
                ('subtotal', models.PositiveIntegerField()),
                ('carrinho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bond.carrinho')),
                ('produto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bond.anuncio')),
            ],
        ),
        migrations.CreateModel(
            name='Transacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tipo_transacao', models.CharField(choices=[('Depósito', 'Depósito'), ('Saque', 'Saque')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_extrato', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
