# Generated by Django 5.2.3 on 2025-06-26 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bond', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoria',
            new_name='Marcas',
        ),
        migrations.RenameField(
            model_name='anuncio',
            old_name='categoria',
            new_name='marca',
        ),
        migrations.RemoveField(
            model_name='anuncio',
            name='data_prazo',
        ),
        migrations.RemoveField(
            model_name='anuncio',
            name='funcao',
        ),
        migrations.RemoveField(
            model_name='anuncio',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='anuncio',
            name='tipo',
        ),
    ]
