# Generated by Django 5.2.3 on 2025-07-01 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bond', '0002_rename_categoria_marcas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='condicao',
            field=models.CharField(choices=[('Novo', 'Novo'), ('Seminovo', 'Seminovo'), ('Usado', 'Usado')], default='Novo', max_length=20),
        ),
    ]
