# Generated by Django 5.2.3 on 2025-07-01 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bond', '0003_anuncio_condicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='marca',
            field=models.CharField(choices=[('Apple', 'Apple'), ('Samsung', 'Samsung'), ('Xiaomi', 'Xiaomi')], default=' ', max_length=20),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='condicao',
            field=models.CharField(choices=[('Novo', 'Novo'), ('Usado', 'Usado'), ('Seminovo', 'Seminovo')], default='Novo', max_length=20),
        ),
        migrations.DeleteModel(
            name='Marcas',
        ),
    ]
