# Generated by Django 5.2.3 on 2025-07-01 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bond', '0004_alter_anuncio_marca_alter_anuncio_condicao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='condicao',
            field=models.CharField(choices=[('Seminovo', 'Seminovo'), ('Usado', 'Usado'), ('Novo', 'Novo')], default='Novo', max_length=20),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='valor',
            field=models.DecimalField(decimal_places=5, max_digits=5),
        ),
    ]
