# Generated by Django 5.2.3 on 2025-07-01 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bond', '0005_alter_anuncio_condicao_alter_anuncio_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='condicao',
            field=models.CharField(choices=[('Seminovo', 'Seminovo'), ('Novo', 'Novo'), ('Usado', 'Usado')], default='Novo', max_length=20),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='marca',
            field=models.CharField(choices=[('Samsung', 'Samsung'), ('Apple', 'Apple'), ('Xiaomi', 'Xiaomi')], default=' ', max_length=20),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='valor',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
    ]
