# Generated by Django 5.2.3 on 2025-07-01 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bond', '0007_alter_anuncio_marca_alter_anuncio_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='condicao',
            field=models.CharField(choices=[('Usado', 'Usado'), ('Novo', 'Novo'), ('Seminovo', 'Seminovo')], default='Novo', max_length=20),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='marca',
            field=models.CharField(choices=[('Apple', 'Apple'), ('Samsung', 'Samsung'), ('Xiaomi', 'Xiaomi')], default=' ', max_length=20),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
