# Generated by Django 5.2.3 on 2025-07-02 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bond', '0008_alter_anuncio_condicao_alter_anuncio_marca_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='avaliacao_anuncio',
            field=models.CharField(default=0, max_length=2),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='condicao',
            field=models.CharField(choices=[('Usado', 'Usado'), ('Seminovo', 'Seminovo'), ('Novo', 'Novo')], default='Novo', max_length=20),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='marca',
            field=models.CharField(choices=[('Samsung', 'Samsung'), ('Apple', 'Apple'), ('Xiaomi', 'Xiaomi')], default=' ', max_length=20),
        ),
    ]
