# Generated by Django 5.2.3 on 2025-07-02 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bond', '0009_alter_anuncio_avaliacao_anuncio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anuncio',
            name='imagem',
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='condicao',
            field=models.CharField(choices=[('Usado', 'Usado'), ('Novo', 'Novo'), ('Seminovo', 'Seminovo')], default='Novo', max_length=20),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='marca',
            field=models.CharField(choices=[('Xiaomi', 'Xiaomi'), ('Apple', 'Apple'), ('Samsung', 'Samsung')], default=' ', max_length=20),
        ),
        migrations.CreateModel(
            name='ImagemAnuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='imagens_produtos/')),
                ('anuncio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='bond.anuncio')),
            ],
        ),
    ]
