# Generated by Django 5.2.3 on 2025-07-04 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bond', '0010_remove_anuncio_imagem_alter_anuncio_condicao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='avaliacao_anuncio',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='condicao',
            field=models.CharField(choices=[('Novo', 'Novo'), ('Seminovo', 'Seminovo'), ('Usado', 'Usado')], default='Novo', max_length=20),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='marca',
            field=models.CharField(choices=[('Samsung', 'Samsung'), ('Apple', 'Apple'), ('Xiaomi', 'Xiaomi')], max_length=20),
        ),
    ]
