# Generated by Django 5.2.3 on 2025-07-04 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bond', '0011_alter_anuncio_avaliacao_anuncio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='armazenamento',
            field=models.CharField(default=' ', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anuncio',
            name='bateria',
            field=models.CharField(default=' ', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anuncio',
            name='camera',
            field=models.CharField(default=' ', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anuncio',
            name='meomoria',
            field=models.CharField(default=' ', max_length=60),
            preserve_default=False,
        ),
    ]
