# Generated by Django 5.2.3 on 2025-07-08 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bond', '0012_anuncio_armazenamento_anuncio_bateria_anuncio_camera_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anuncio',
            old_name='meomoria',
            new_name='memoria',
        ),
    ]
