# Generated by Django 5.2.3 on 2025-07-18 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bond', '0013_rename_meomoria_anuncio_memoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerguntasFrequentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.CharField(max_length=200)),
                ('respostas', models.CharField(max_length=500)),
            ],
        ),
    ]
